// migrate-kb.mjs — One-time knowledge base migration script
// Run from ~/dtf-field-ops: node migrate-kb.mjs
// Delete this file after successful migration

import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'

// Read credentials from existing .env.local
const envFile = readFileSync('.env.local', 'utf8')
const env = {}
envFile.split('\n').forEach(line => {
  const [key, ...vals] = line.split('=')
  if (key && key.trim()) env[key.trim()] = vals.join('=').trim()
})

const supabase = createClient(env.VITE_SUPABASE_URL, env.VITE_SUPABASE_ANON_KEY)

const sourceFiles = [
  { id: '3ac9eb64-50ba-4950-8b1d-d19bee9efb53', file_name: 'about-20260202.txt',    file_type: 'text/plain', file_size: 4471808, upload_status: 'active', location_id: 'default', category: 'About'    },
  { id: '8eb1ce30-bc8d-4cff-81bf-d8fb93bb0afc', file_name: 'process-20260202.txt',  file_type: 'text/plain', file_size: 1673216, upload_status: 'active', location_id: 'default', category: 'Process'  },
  { id: '20ccd867-2f06-48f1-a006-d601e266ea5b', file_name: 'faq-20260202.txt',      file_type: 'text/plain', file_size: 3435520, upload_status: 'active', location_id: 'default', category: 'FAQ'      },
  { id: '3fecf755-e67f-40cc-8a60-6c7c7e3298e9', file_name: 'warranty-20260202.txt', file_type: 'text/plain', file_size: 985088,  upload_status: 'active', location_id: 'default', category: 'Warranty' },
  { id: '09e939c5-0a91-4ae6-8a36-9768cb2a0a11', file_name: 'services-20260202.txt', file_type: 'text/plain', file_size: 4912128, upload_status: 'active', location_id: 'default', category: 'Services' },
  { id: '3d97d3e8-0f68-4563-8c19-7f60f36ef95e', file_name: 'policies-20260202.txt', file_type: 'text/plain', file_size: 2540544, upload_status: 'active', location_id: 'default', category: 'Policies' },
  { id: '7182bf21-3468-41bc-9080-d62af8e8524c', file_name: 'pricing-20260202.txt',  file_type: 'text/plain', file_size: 2893824, upload_status: 'active', location_id: 'default', category: 'Pricing'  },
]

const knowledgeBase = [
  { id: '53e842a2-f684-4f5e-9764-7a0e9a003b15', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 62, from: 18 } }, source: 'about-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nSERVICE AREA\n================================================================================\n\nBase Location: Lavon, TX (395 Orbit Drive, Lavon, TX 75166)\n\nService Area: All locations within approximately 1 hour driving distance from Lavon, TX.\n\nTravel Fee: $35 non-refundable fee for locations beyond 1-hour driving distance.\n\nWe service the entire Dallas-Fort Worth Metroplex including:\n• Dallas\n• Fort Worth\n• Plano\n• Frisco\n• McKinney\n• Allen\n• Richardson\n• Garland\n• Mesquite\n• Irving\n• Arlington\n• Denton\n• Wylie\n• Rockwall\n• And surrounding areas\n\n================================================================================\nWHY CHOOSE DALLAS TUB FIX\n================================================================================\n\n1. INDUSTRY-LEADING 2-YEAR WARRANTY\n   Most competitors offer 1 year or no warranty. Our 2-year warranty shows we stand behind our work.\n\n2. TRANSPARENT PRICING\n   Our prices are listed on our website. No surprises, no haggling, no hidden fees.\n\n3. SPECIALIZED EXPERTISE\n   We offer fiberglass bottom repair—a service most companies can't do or don't know exists.\n\n4. SAVE THOUSANDS\n   Repair costs $385-$585 vs. replacement costs of $1,500-$5,000+. Most repairs save 70-90% compared to replacement.\n\n5. MINIMAL DISRUPTION\n   1-3 hours and your tub is ready the next morning. No demolition, no contractors, no mess.` },
  { id: '0d7f4209-d078-4076-bf2e-b0831c1c803f', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 101, from: 74 } }, source: 'about-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Business Name: Dallas Tub Fix\nPhone: (469) 592-0018\nEmail: info@dallastubfix.com\nWebsite: https://dallastubfix.com\n\nLocation: Lavon, TX 75166\nService Area: Dallas-Fort Worth Metroplex (within ~1 hour of Lavon)\n\nHours: By Appointment Only (Thursdays & Fridays)\n\n================================================================================\nFOR THE CHAT BOT - RESPONSE GUIDELINES\n================================================================================\n\nWhen answering customer questions:\n\n1. Be friendly, professional, and helpful\n2. Use the exact pricing from this document—do not estimate or round\n3. If asked about services we don't offer (refinishing, tile), politely explain we specialize in repairs only and recommend they find a refinishing specialist\n4. If damage severity is unclear, encourage the customer to send photos or book an assessment\n5. Do NOT determine if damage is "too severe"—that decision is made by the business owner\n6. For bulk bookings, direct customers to call—bulk bookings cannot be made through chat\n7. Always mention the 2-year warranty as a key differentiator\n8. For color matching questions, always disclose the up-to-10% variation possibility\n\n================================================================================\nEND OF DOCUMENT\n================================================================================` },
  { id: '5d261e60-81de-47a6-94dc-5b37f05c701c', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 88, from: 52 } }, source: 'about-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `2. TRANSPARENT PRICING\n   Our prices are listed on our website. No surprises, no haggling, no hidden fees.\n\n3. SPECIALIZED EXPERTISE\n   We offer fiberglass bottom repair—a service most companies can't do or don't know exists.\n\n4. SAVE THOUSANDS\n   Repair costs $385-$585 vs. replacement costs of $1,500-$5,000+. Most repairs save 70-90% compared to replacement.\n\n5. MINIMAL DISRUPTION\n   1-3 hours and your tub is ready the next morning. No demolition, no contractors, no mess.\n\n6. LOCAL OWNER-OPERATED\n   Not a franchise. You deal directly with the person doing the work. Accountability and quality you can trust.\n\n7. PROPERTY MANAGER FRIENDLY\n   Bulk discounts available. Reliable scheduling for multi-unit properties.\n\n================================================================================\nCONTACT INFORMATION\n================================================================================\n\nBusiness Name: Dallas Tub Fix\nPhone: (469) 592-0018\nEmail: info@dallastubfix.com\nWebsite: https://dallastubfix.com\n\nLocation: Lavon, TX 75166\nService Area: Dallas-Fort Worth Metroplex (within ~1 hour of Lavon)\n\nHours: By Appointment Only (Thursdays & Fridays)` },
  { id: 'c5b08680-bb65-42b5-b610-d7aaae8cca74', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 101, from: 74 } }, source: 'about-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Business Name: Dallas Tub Fix\nPhone: (469) 592-0018\nEmail: info@dallastubfix.com\nWebsite: https://dallastubfix.com\n\nLocation: Lavon, TX 75166\nService Area: Dallas-Fort Worth Metroplex (within ~1 hour of Lavon)\n\nHours: By Appointment Only (Thursdays & Fridays)\n\n================================================================================\nFOR THE CHAT BOT - RESPONSE GUIDELINES\n================================================================================\n\nWhen answering customer questions:\n\n1. Be friendly, professional, and helpful\n2. Use the exact pricing from this document—do not estimate or round\n3. If asked about services we don't offer (refinishing, tile), politely explain we specialize in repairs only and recommend they find a refinishing specialist\n4. If damage severity is unclear, encourage the customer to send photos or book an assessment\n5. Do NOT determine if damage is "too severe"—that decision is made by the business owner\n6. For bulk bookings, direct customers to call—bulk bookings cannot be made through chat\n7. Always mention the 2-year warranty as a key differentiator\n8. For color matching questions, always disclose the up-to-10% variation possibility\n\n================================================================================\nEND OF DOCUMENT\n================================================================================` },
  { id: 'b8b791ff-0b53-44fe-a6aa-d69a8b9e3490', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 88, from: 52 } }, source: 'about-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `2. TRANSPARENT PRICING\n   Our prices are listed on our website. No surprises, no haggling, no hidden fees.\n\n3. SPECIALIZED EXPERTISE\n   We offer fiberglass bottom repair—a service most companies can't do or don't know exists.\n\n4. SAVE THOUSANDS\n   Repair costs $385-$585 vs. replacement costs of $1,500-$5,000+. Most repairs save 70-90% compared to replacement.\n\n5. MINIMAL DISRUPTION\n   1-3 hours and your tub is ready the next morning. No demolition, no contractors, no mess.\n\n6. LOCAL OWNER-OPERATED\n   Not a franchise. You deal directly with the person doing the work. Accountability and quality you can trust.\n\n7. PROPERTY MANAGER FRIENDLY\n   Bulk discounts available. Reliable scheduling for multi-unit properties.` },
  { id: '6b105e5f-5bab-440c-929c-3e39a6042162', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 26, from: 1 } }, source: 'about-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nDALLAS TUB FIX - ABOUT US\n================================================================================\nLast Updated: January 23, 2026\n\n================================================================================\nBUSINESS OVERVIEW\n================================================================================\n\nBusiness Name: Dallas Tub Fix\nTagline: "Expert Repairs. 2-Year Warranty."\nExtended Tagline: "Professional Bathtub & Fiberglass Repair—Backed by a 2-Year Warranty"\n\nDallas Tub Fix is a professional bathtub and fiberglass repair service based in Lavon, TX. We specialize in repairing chips, cracks, holes, scratches, burns, and structural damage to bathtubs, shower floors, fiberglass enclosures, cultured marble, sinks, and high-end toilets.\n\nWe focus exclusively on REPAIRS—not full refinishing or reglazing. This allows us to save homeowners thousands of dollars compared to full replacement while delivering professional, lasting results backed by an industry-leading 2-year warranty.` },
  { id: '00fa4d45-5c0f-45a9-9ef2-68595fa16c2e', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 62, from: 18 } }, source: 'about-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nSERVICE AREA\n================================================================================\n\nBase Location: Lavon, TX (395 Orbit Drive, Lavon, TX 75166)\n\nService Area: All locations within approximately 1 hour driving distance from Lavon, TX.\n\nTravel Fee: $35 non-refundable fee for locations beyond 1-hour driving distance.\n\nWe service the entire Dallas-Fort Worth Metroplex including:\n• Dallas\n• Fort Worth\n• Plano\n• Frisco\n• McKinney\n• Allen\n• Richardson\n• Garland\n• Mesquite\n• Irving\n• Arlington\n• Denton\n• Wylie\n• Rockwall\n• And surrounding areas` },
  { id: 'b6eb05c4-a51c-4039-ac25-f2f406d252f3', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 26, from: 1 } }, source: 'about-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nDALLAS TUB FIX - ABOUT US\n================================================================================\nLast Updated: January 23, 2026\n\n================================================================================\nBUSINESS OVERVIEW\n================================================================================\n\nBusiness Name: Dallas Tub Fix\nTagline: "Expert Repairs. 2-Year Warranty."\n\nDallas Tub Fix is a professional bathtub and fiberglass repair service based in Lavon, TX. We specialize in repairing chips, cracks, holes, scratches, burns, and structural damage to bathtubs, shower floors, fiberglass enclosures, cultured marble, sinks, and high-end toilets.\n\nWe focus exclusively on REPAIRS—not full refinishing or reglazing.` },
  { id: 'd978c5d2-fb57-4555-850c-ccf3db2857a4', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 38, from: 1 } }, source: 'process-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nDALLAS TUB FIX - REPAIR PROCESS\n================================================================================\nLast Updated: January 23, 2026\n\n================================================================================\nWHAT TO EXPECT - THE REPAIR PROCESS\n================================================================================\n\nBefore Your Appointment:\n• Clear all personal items from the tub/shower area\n• No need to clean the tub—we handle all preparation\n• We will mask off and protect all surrounding surfaces from overspray\n\nDuring the Repair:\n• Most repairs take 1-3 hours depending on damage\n• We bring all materials and equipment\n• Minimal disruption to your home\n• No demolition, no mess\n\nAfter the Repair:\n• Tub is ready for light use after 6 hours\n• Full use the next morning\n• We clean up completely before leaving\n\n================================================================================\nCOMMON CAUSES OF DAMAGE\n================================================================================\n\nWe commonly repair damage caused by:\n\n• Dropped items (shampoo bottles, razors, tools)\n• Age and normal wear over time\n• Manufacturing defects\n• Handicap benches and bath seats (common with elderly users)\n• Impact from hard objects\n• Improper cleaning products\n• Heat damage (hot styling tools, cigarettes)` },
  { id: '06e04e6e-3fa7-4068-9306-ec7abde548c7', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 42, from: 26 } }, source: 'process-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nCOMMON CAUSES OF DAMAGE\n================================================================================\n\nWe commonly repair damage caused by:\n\n• Dropped items (shampoo bottles, razors, tools)\n• Age and normal wear over time\n• Manufacturing defects\n• Handicap benches and bath seats (common with elderly users)\n• Impact from hard objects\n• Improper cleaning products\n• Heat damage (hot styling tools, cigarettes)\n\n================================================================================\nEND OF DOCUMENT\n================================================================================` },
  { id: '7b737329-6d24-4d6c-9bff-701cf1663d3d', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 42, from: 26 } }, source: 'process-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nCOMMON CAUSES OF DAMAGE\n================================================================================\n\nWe commonly repair damage caused by:\n\n• Dropped items (shampoo bottles, razors, tools)\n• Age and normal wear over time\n• Manufacturing defects\n• Handicap benches and bath seats\n• Impact from hard objects\n• Improper cleaning products\n• Heat damage (hot styling tools, cigarettes)\n\n================================================================================\nEND OF DOCUMENT\n================================================================================` },
  { id: '740d6265-2f3e-440e-bdc8-6c3dc9570681', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 38, from: 1 } }, source: 'process-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nDALLAS TUB FIX - REPAIR PROCESS\n================================================================================\n\nBefore Your Appointment:\n• Clear all personal items from the tub/shower area\n• No need to clean the tub—we handle all preparation\n• We will mask off and protect all surrounding surfaces\n\nDuring the Repair:\n• Most repairs take 1-3 hours depending on damage\n• We bring all materials and equipment\n• Minimal disruption to your home\n\nAfter the Repair:\n• Tub is ready for light use after 6 hours\n• Full use the next morning\n• We clean up completely before leaving` },
  { id: '93a49496-1958-4606-ab50-8c90e5f3d084', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 47, from: 22 } }, source: 'faq-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Q: Do you repair tile?\nA: No, we do not work on tile. We only repair bathtubs, fiberglass, cultured marble, sinks, and toilets.\n\nQ: Will the repair match my tub's color?\nA: We do our best to match your existing color, but we cannot guarantee an exact match. Color may vary by up to 10% due to age, fading, and manufacturer differences.\n\nQ: What's your warranty?\nA: All repairs come with a 2-year warranty covering materials and labor—one of the best in the industry.\n\nQ: Do you require a deposit?\nA: Only if you need a non-standard color. Standard colors (Lasco White/Almond, Kohler White/Almond, Black, Pure White) require no deposit.\n\nQ: What payment methods do you accept?\nA: Cash, check, credit/debit card (Square), and Zelle. Payment is due upon completion.\n\nQ: How far in advance can I book?\nA: Up to 1 month in advance. We're available Thursdays and Fridays.\n\nQ: Is there a travel fee?\nA: No travel fee within 1-hour driving distance of Lavon, TX. Beyond that, a $35 non-refundable travel fee applies.\n\nQ: Do you offer discounts for multiple jobs?\nA: Yes! 10% off for 2+ jobs, 20% off for 5+ jobs, and 35% off for 10+ jobs—all must be booked at the same time by phone.\n\nQ: What should I do before you arrive?\nA: Just clear personal items from the tub/shower area. No need to clean—we handle all preparation.` },
  { id: '7ae487af-8c09-480d-bdb9-d5f94bf8df66', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 29, from: 1 } }, source: 'faq-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nDALLAS TUB FIX - FREQUENTLY ASKED QUESTIONS\n================================================================================\nLast Updated: January 23, 2026\n\nQ: How much does bathtub repair cost?\nA: Small repairs (chips, scratches, burns) are $385. Large repairs (cracks, holes, structural) are $585. Fiberglass bottom repair is $585. All prices include materials.\n\nQ: How long does the repair take?\nA: Most repairs are completed in 1-3 hours.\n\nQ: When can I use my tub after repair?\nA: Light use after 6 hours. Full use the next morning.\n\nQ: Do you offer full bathtub refinishing?\nA: No, we specialize in repairs only. For full refinishing, we recommend finding a company that specializes in refinishing.\n\nQ: Do you repair tile?\nA: No, we do not work on tile. We only repair bathtubs, fiberglass, cultured marble, sinks, and toilets.\n\nQ: Will the repair match my tub's color?\nA: We do our best to match your existing color, but we cannot guarantee an exact match. Color may vary by up to 10%.` },
  { id: '548e19bf-3815-47d4-9b33-961789941f1e', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 47, from: 22 } }, source: 'faq-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Q: Do you repair tile?\nA: No. We only repair bathtubs, fiberglass, cultured marble, sinks, and toilets.\n\nQ: Will the repair match my tub's color?\nA: We do our best but cannot guarantee exact match. Color may vary by up to 10%.\n\nQ: What's your warranty?\nA: 2-year warranty covering materials and labor.\n\nQ: Do you require a deposit?\nA: Only for non-standard colors. Standard colors require no deposit.\n\nQ: What payment methods do you accept?\nA: Cash, check, credit/debit card (Square), and Zelle. Payment due upon completion.\n\nQ: How far in advance can I book?\nA: Up to 1 month. Available Thursdays and Fridays.\n\nQ: Is there a travel fee?\nA: No fee within 1-hour drive of Lavon, TX. Beyond that, $35 applies.` },
  { id: '6a8a7665-a334-4124-8aa3-510981d61dfa', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 63, from: 40 } }, source: 'faq-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Q: Is there a travel fee?\nA: No travel fee within 1-hour driving distance of Lavon, TX. Beyond that, a $35 non-refundable travel fee applies.\n\nQ: Do you offer discounts for multiple jobs?\nA: Yes! 10% off for 2+ jobs, 20% off for 5+ jobs, and 35% off for 10+ jobs—all must be booked at the same time by phone.\n\nQ: What should I do before you arrive?\nA: Just clear personal items from the tub/shower area. No need to clean—we handle all preparation.\n\nQ: Can you tell from photos if my tub can be repaired?\nA: Yes, in most cases we can assess damage from photos. Send photos to info@dallastubfix.com or through our chat widget for a quote.\n\nQ: What if the damage is too severe to repair?\nA: Some damage is beyond repair. This would be determined in person or from photos. If we can't repair it, we'll let you know honestly.\n\nQ: Do you work with property managers?\nA: Absolutely! We offer bulk discounts and reliable scheduling for property managers and landlords with multiple units.\n\nQ: What if my tub floor is soft and spongy?\nA: This is exactly what our fiberglass bottom repair service addresses. We cut out the damaged area, install new bracing, and restore the floor to solid, safe condition. Price is $585.` },
  { id: '7ff2633c-0771-4406-ac43-d6802494c380', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 29, from: 1 } }, source: 'faq-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nDALLAS TUB FIX - FREQUENTLY ASKED QUESTIONS\n================================================================================\n\nQ: How much does bathtub repair cost?\nA: Small repairs (chips, scratches, burns) are $385. Large repairs (cracks, holes, structural) are $585. Fiberglass bottom repair is $585. All prices include materials.\n\nQ: How long does the repair take?\nA: Most repairs are completed in 1-3 hours.\n\nQ: When can I use my tub after repair?\nA: Light use after 6 hours. Full use the next morning.\n\nQ: Do you offer full bathtub refinishing?\nA: No, we specialize in repairs only.\n\nQ: Do you repair tile?\nA: No. We only repair bathtubs, fiberglass, cultured marble, sinks, and toilets.\n\nQ: What's your warranty?\nA: All repairs come with a 2-year warranty covering materials and labor.` },
  { id: '246dc591-5cfe-4d32-bf75-dc19309f89f5', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 63, from: 40 } }, source: 'faq-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Q: Is there a travel fee?\nA: No travel fee within 1-hour driving distance of Lavon, TX. Beyond that, a $35 non-refundable travel fee applies.\n\nQ: Do you offer discounts for multiple jobs?\nA: Yes! 10% off for 2+ jobs, 20% off for 5+ jobs, and 35% off for 10+ jobs—all must be booked at the same time by phone.\n\nQ: Can you tell from photos if my tub can be repaired?\nA: Yes, in most cases. Send photos to info@dallastubfix.com or through our chat widget.\n\nQ: Do you work with property managers?\nA: Absolutely! Bulk discounts and reliable scheduling for property managers.\n\nQ: What if my tub floor is soft and spongy?\nA: This is our fiberglass bottom repair service. We cut out the damaged area, install new bracing, and restore the floor. Price is $585.` },
  { id: '069eaeac-f7e3-41c2-af88-a46d20918833', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 26, from: 1 } }, source: 'warranty-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nDALLAS TUB FIX - WARRANTY\n================================================================================\nLast Updated: January 23, 2026\n\nALL work is backed by our 2-YEAR WARRANTY.\n\nThis is one of the best warranties in the repair industry. Most competitors offer 1 year or no warranty at all.\n\nWarranty covers:\n• All materials used\n• All labor performed\n• Repair failure due to workmanship\n\nWarranty does NOT cover:\n• New damage from impacts or misuse\n• Normal wear and tear\n• Damage from improper cleaning products\n\n================================================================================\nEND OF DOCUMENT\n================================================================================` },
  { id: '0ccdaddf-3440-45b5-81b5-2d27cd311a71', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 26, from: 1 } }, source: 'warranty-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nDALLAS TUB FIX - WARRANTY\n================================================================================\n\nALL work is backed by our 2-YEAR WARRANTY.\n\nMost competitors offer 1 year or no warranty at all.\n\nWarranty covers:\n• All materials used\n• All labor performed\n• Repair failure due to workmanship\n\nWarranty does NOT cover:\n• New damage from impacts or misuse\n• Normal wear and tear\n• Damage from improper cleaning products` },
  { id: '77628298-9a67-47c7-bcff-1f08fca02c60', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 118, from: 101 } }, source: 'services-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nSERVICES NOT OFFERED\n================================================================================\n\nWe do NOT offer the following services:\n\n• Full bathtub refinishing or reglazing\n• Tile repair or tile work of any kind\n• Countertop refinishing\n• Full surface recoating\n• Bathtub replacement\n• Plumbing services\n\nIf you need full refinishing, we recommend finding a company that specializes in bathtub refinishing. Our focus is repairs only.\n\n================================================================================\nEND OF DOCUMENT\n================================================================================` },
  { id: 'cc7370f8-aaf9-477e-9e39-35f06754d8da', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 29, from: 1 } }, source: 'services-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nDALLAS TUB FIX - SERVICES\n================================================================================\nLast Updated: January 23, 2026\n\nSERVICES OFFERED\n\n----- SMALL REPAIRS - $385 -----\n\nSmall repairs address cosmetic damage that does not affect the structural integrity of the tub or surface. These include:\n\n• Chip repair - Small chips from dropped items or impact\n• Scratch repair - Surface scratches from cleaning or normal use\n• Burn marks - Cigarette burns or heat damage\n• Small holes - Holes approximately the size of a doorknob or smaller\n• Scuff marks - Surface scuffs from normal wear\n• Hairline cracks (non-flexing) - Fine surface cracks that do not flex when pressure is applied\n• Minor surface damage - General cosmetic imperfections\n\nMost porcelain tub repairs fall into this category because porcelain sits on top of cast iron, making structural damage extremely rare.\n\nPrice: $385 (all materials included)` },
  { id: '93ae1925-d29e-4225-a6ef-4d5eb70f7a5d', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 49, from: 22 } }, source: 'services-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Price: $385 (all materials included)\n\n----- LARGE REPAIRS - $585 -----\n\nLarge repairs address damage that affects or could affect the structural integrity or functionality of the tub:\n\n• Large cracks with flexing - Cracks that move when pressure is applied\n• Holes larger than a doorknob - Significant punctures or breaks\n• Multiple areas of damage - Several repair spots needed\n• Structural damage - Anything compromising the tub's integrity\n• Bottom/floor damage - Cracks or damage on the tub floor (not fiberglass soft floors)\n\nPrice: $585 (all materials included)\n\n----- FIBERGLASS BOTTOM REPAIR - $585 -----\n\nThis is a specialty service that very few companies know how to perform. Fiberglass bottom repair addresses soft, spongy, or cracked fiberglass shower and tub floors.\n\nHow fiberglass bottom damage occurs:\n1. Most fiberglass tub/shower floors are braced underneath with a single sheet of plywood\n2. Over time, small hairline cracks develop from normal flexing during use\n3. Water seeps through these cracks and begins deteriorating the plywood\n4. The floor becomes soft, spongy, and unsafe\n5. If left untreated, cracks can spread to sidewalls making repair impossible` },
  { id: '4abf5065-bc6a-4106-a212-6c76bb2d05a7', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 81, from: 44 } }, source: 'services-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Our fiberglass bottom repair process:\n1. Cut out the damaged area\n2. Install new structural bracing\n3. Patch and seal\n4. Apply resin and cure\n5. Sand smooth\n6. Paint and finish\n\nImportant: If the crack has already reached the sidewall, repair costs exceed replacement costs. At that point, replacement is recommended.\n\nNote: If a hairline crack on a fiberglass floor does NOT flex when pressed, it is simply a cosmetic small repair ($385), not a structural fiberglass bottom repair.\n\nPrice: $585 (all materials included)\n\n----- CULTURED MARBLE REPAIR - $385 / $585 -----\n\nWe repair chips, cracks, and damage to cultured marble surfaces including vanity tops, tub surrounds, and shower walls.\n\n• Small cultured marble repairs (cosmetic): $385\n• Large cultured marble repairs (structural): $585\n\n----- SINK AND TOILET CHIP REPAIR - $385 -----\n\nWe repair chips in:\n• Bathroom sinks\n• Kitchen sinks\n• High-end toilets (where repair cost is less than replacement cost)` },
  { id: 'bc86563e-4ed8-487f-bed9-c835ce031308', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 112, from: 66 } }, source: 'services-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `SURFACES WE WORK ON\n\nWe repair ALL bathtub and surface types:\n\n• Fiberglass tubs and showers\n• Acrylic tubs and showers\n• Porcelain tubs\n• Porcelain-over-cast-iron tubs\n• Cast iron tubs\n• Cultured marble\n• Bathroom sinks\n• Kitchen sinks\n• High-end toilets\n\nSERVICES NOT OFFERED\n\nWe do NOT offer:\n• Full bathtub refinishing or reglazing\n• Tile repair or tile work of any kind\n• Countertop refinishing\n• Full surface recoating\n• Bathtub replacement\n• Plumbing services` },
  { id: '6680ada8-0f4f-4b1a-842d-28ae007a147f', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 118, from: 101 } }, source: 'services-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `SERVICES NOT OFFERED\n\nWe do NOT offer the following services:\n\n• Full bathtub refinishing or reglazing\n• Tile repair or tile work of any kind\n• Countertop refinishing\n• Full surface recoating\n• Bathtub replacement\n• Plumbing services\n\nIf you need full refinishing, we recommend finding a company that specializes in bathtub refinishing. Our focus is repairs only.` },
  { id: '94214dff-66f5-49ba-bf59-b81a38a10bcc', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 29, from: 1 } }, source: 'services-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `DALLAS TUB FIX - SERVICES\n\nSERVICES OFFERED\n\n----- SMALL REPAIRS - $385 -----\n\n• Chip repair\n• Scratch repair\n• Burn marks\n• Small holes (doorknob size or smaller)\n• Scuff marks\n• Hairline cracks (non-flexing)\n• Minor surface damage\n\nPrice: $385 (all materials included)\n\n----- LARGE REPAIRS - $585 -----\n\n• Large cracks with flexing\n• Holes larger than a doorknob\n• Multiple areas of damage\n• Structural damage\n• Bottom/floor damage` },
  { id: '78957e1f-f19f-4669-9220-d2646c68553e', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 81, from: 44 } }, source: 'services-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Fiberglass bottom damage occurs when:\n1. Plywood bracing deteriorates from water seeping through hairline cracks\n2. The floor becomes soft, spongy, and unsafe\n3. If untreated, cracks spread to sidewalls\n\nOur repair process:\n1. Cut out the damaged area\n2. Install new structural bracing\n3. Patch and seal\n4. Apply resin and cure\n5. Sand smooth\n6. Paint and finish\n\nPrice: $585 (all materials included)\n\nCultured marble, sink, and toilet repairs also available.` },
  { id: 'afd07ab3-2e97-462f-8a7b-236786861b5e', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 49, from: 22 } }, source: 'services-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `LARGE REPAIRS - $585\n\nAddresses damage affecting structural integrity:\n\n• Large cracks with flexing\n• Holes larger than a doorknob\n• Multiple areas of damage\n• Structural damage\n• Bottom/floor damage\n\nPrice: $585 (all materials included)\n\nFIBERGLASS BOTTOM REPAIR - $585\n\nSpecialty service for soft, spongy, or cracked fiberglass shower and tub floors. Very few companies offer this service.\n\nHow damage occurs:\n1. Plywood bracing underneath deteriorates from water seeping through hairline cracks\n2. Floor becomes soft, spongy, and unsafe\n3. If untreated, cracks spread to sidewalls making repair impossible` },
  { id: 'cdc27103-45e2-4db7-8fbf-0bf805fa7f50', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 112, from: 66 } }, source: 'services-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `CULTURED MARBLE REPAIR - $385 / $585\n\nWe repair chips, cracks, and damage to cultured marble surfaces.\n\n• Small (cosmetic): $385\n• Large (structural): $585\n\nSINK AND TOILET CHIP REPAIR - $385\n\nWe repair chips in bathroom sinks, kitchen sinks, and high-end toilets.\n\nSURFACES WE WORK ON:\n• Fiberglass tubs and showers\n• Acrylic tubs and showers\n• Porcelain tubs\n• Cast iron tubs\n• Cultured marble\n• Bathroom and kitchen sinks\n• High-end toilets` },
  { id: 'c5b4d979-2c58-4471-8966-6862723ef120', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 45, from: 1 } }, source: 'policies-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `================================================================================\nDALLAS TUB FIX - POLICIES\n================================================================================\nLast Updated: January 23, 2026\n\nSCHEDULING\n\nAvailability: Thursdays and Fridays only.\nBooking Window: Up to 1 month in advance.\nAppointment Confirmation: We will confirm via text or email.\n\nCANCELLATION POLICY\n\nPlease cancel within 24 hours of your scheduled appointment.\n\nPAYMENT\n\nPayment Methods Accepted:\n• Cash\n• Check\n• Credit/Debit Card (Square)\n• Zelle\n\nPayment is due upon completion of the repair.\n\nDeposit Requirement: A deposit is ONLY required if you need a special color.\n\nStandard colors (no deposit required):\n• Lasco White\n• Lasco Almond\n• Kohler White\n• Kohler Almond\n• Black\n• Pure White` },
  { id: 'e4e07f0c-f38d-42ea-8b15-433d5f7d125f', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 63, from: 28 } }, source: 'policies-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Payment Methods Accepted:\n• Cash\n• Check\n• Credit/Debit Card (Square)\n• Zelle\n\nPayment is due upon completion.\n\nFor custom or non-standard colors, a deposit will be required to cover special-order materials.\n\nCOLOR MATCHING DISCLOSURE\n\nIMPORTANT: We cannot guarantee an exact color match.\n\nWe do our best to match your tub's existing color. However, due to age, fading, lighting, and manufacturer variations, color can vary by up to 10%.\n\nFor repairs, this slight variation is typically not noticeable. If you require a perfectly uniform color, we recommend a company that offers full bathtub refinishing.\n\nThis disclosure will be communicated before any repair work begins.` },
  { id: '41c053e5-08d8-4329-a154-dfb7b715b89c', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 45, from: 1 } }, source: 'policies-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `DALLAS TUB FIX - POLICIES\n\nSCHEDULING\nAvailability: Thursdays and Fridays only.\nBooking Window: Up to 1 month in advance.\n\nCANCELLATION POLICY\nPlease cancel within 24 hours of your scheduled appointment.\n\nPAYMENT\nAccepted: Cash, Check, Credit/Debit Card (Square), Zelle\nPayment due upon completion.\nDeposit only required for non-standard colors.\n\nStandard colors (no deposit):\n• Lasco White / Almond\n• Kohler White / Almond\n• Black\n• Pure White` },
  { id: 'a45e56a5-e252-4136-8e24-558668d58b77', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 63, from: 28 } }, source: 'policies-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `Payment methods: Cash, Check, Credit/Debit Card (Square), Zelle.\nPayment due upon completion.\n\nCOLOR MATCHING DISCLOSURE\n\nWe cannot guarantee an exact color match. Color may vary by up to 10% due to age, fading, and manufacturer differences.\n\nThis disclosure will be communicated before any repair work begins.` },
  { id: '76894942-cefb-48f0-a7dc-3352950b1936', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 76, from: 59 } }, source: 'pricing-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `BULK DISCOUNTS\n\nDiscounts for multiple jobs booked at the same time:\n\n• 2+ jobs: 10% off each job\n• 5+ jobs: 20% off each job\n• 10+ jobs: 35% off each job\n\nRequirements:\n• All jobs must be booked at the same time\n• Bulk bookings must be made over the phone, not through the chat widget\n• Ideal for property managers and landlords with multiple units` },
  { id: '6a02247f-31a7-4529-8115-4dd5d41ac677', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 67, from: 26 } }, source: 'pricing-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `PRICING SUMMARY\n\nAll prices include materials. No hidden fees.\n\n| Service                    | Price |\n|----------------------------|-------|\n| Small Repair               | $385  |\n| Large Repair               | $585  |\n| Fiberglass Bottom Repair   | $585  |\n| Cultured Marble (Small)    | $385  |\n| Cultured Marble (Large)    | $585  |\n| Sink/Toilet Chip Repair    | $385  |\n| Travel Fee (beyond 1 hour) | $35   |\n\nBULK DISCOUNTS (must book by phone):\n• 2+ jobs: 10% off\n• 5+ jobs: 20% off\n• 10+ jobs: 35% off` },
  { id: 'fffa1731-5eb0-47bf-aacf-0278c00bdadf', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 76, from: 59 } }, source: 'pricing-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `BULK DISCOUNTS\n\n• 2+ jobs: 10% off each job\n• 5+ jobs: 20% off each job\n• 10+ jobs: 35% off each job\n\nAll jobs must be booked at the same time by phone.\nIdeal for property managers and landlords.` },
  { id: '804e73b6-4bef-44f2-bb34-2afd378f4e3a', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 41, from: 1 } }, source: 'pricing-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `DALLAS TUB FIX - PRICING\n\nREPAIR PRICES (All materials included, no hidden fees):\n\n• SMALL REPAIRS: $385\n  - Chips, scratches, burns, small holes, scuff marks, hairline cracks\n\n• LARGE REPAIRS: $585\n  - Cracks with flexing, holes larger than a doorknob, multiple damage areas, structural damage\n\n• FIBERGLASS BOTTOM REPAIR: $585\n  - Soft, spongy, or cracked fiberglass shower/tub floors\n\n• CULTURED MARBLE: $385 (small) / $585 (large)\n\n• SINK/TOILET CHIP REPAIR: $385\n\n• TRAVEL FEE: $35 (only beyond 1-hour drive from Lavon, TX)\n\nAll work backed by our industry-leading 2-YEAR WARRANTY.` },
  { id: '4d468e22-4bcf-455b-b5bc-5311954fe223', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 41, from: 1 } }, source: 'pricing-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `DALLAS TUB FIX - PRICING QUICK REFERENCE\n\n• SMALL REPAIRS: $385 — chips, scratches, burns, small holes, hairline cracks\n• LARGE REPAIRS: $585 — flexing cracks, large holes, structural damage\n• FIBERGLASS BOTTOM REPAIR: $585 — soft/spongy floors\n• CULTURED MARBLE: $385/$585\n• SINK/TOILET: $385\n• TRAVEL FEE: $35 (beyond 1 hour from Lavon)\n\nBULK: 10% off 2+, 20% off 5+, 35% off 10+ (phone only)\n\nAll work includes 2-YEAR WARRANTY.` },
  { id: '5f818523-b817-4360-b929-7ac52f7d2361', location_id: 'dtf', status: 'active', metadata: { loc: { lines: { to: 67, from: 26 } }, source: 'pricing-20260202.txt', status: 'active', blobType: 'text/plain' }, content: `PRICING SUMMARY — All prices include materials, no hidden fees.\n\nSmall Repair: $385\nLarge Repair: $585\nFiberglass Bottom Repair: $585\nCultured Marble Small: $385\nCultured Marble Large: $585\nSink/Toilet Chip Repair: $385\nTravel Fee (beyond 1 hr): $35\n\nBulk discounts available by phone for 2+, 5+, and 10+ jobs.` },
]

async function migrate() {
  console.log('Starting knowledge base migration...\n')

  // Insert source files
  console.log('Inserting source_files...')
  const { error: sfError } = await supabase.from('source_files').insert(sourceFiles)
  if (sfError) {
    console.error('source_files error:', sfError.message)
  } else {
    console.log(`✓ ${sourceFiles.length} source files inserted`)
  }

  // Insert knowledge base in batches of 10
  console.log('\nInserting knowledge_base records...')
  const batchSize = 10
  let inserted = 0
  for (let i = 0; i < knowledgeBase.length; i += batchSize) {
    const batch = knowledgeBase.slice(i, i + batchSize)
    const { error } = await supabase.from('knowledge_base').insert(batch)
    if (error) {
      console.error(`Batch ${i}-${i+batchSize} error:`, error.message)
    } else {
      inserted += batch.length
      console.log(`✓ Inserted records ${i+1}-${Math.min(i+batchSize, knowledgeBase.length)}`)
    }
  }

  console.log(`\n✓ Migration complete: ${inserted}/${knowledgeBase.length} knowledge base records inserted`)
  console.log('\nNext step: Deploy Edge Functions, then generate embeddings via the archive-agent endpoint.')
  console.log('Delete this file after confirming the migration succeeded.')
}

migrate().catch(console.error)